package mcpclient

import (
	"context"
	"fmt"
	"math"
	"testing"

	"pgregory.net/rapid"
)

// Feature: mcp-client-integration, Property 9: Store data constructs correct tool parameters
// **Validates: Requirements 4.1, 4.2, 4.3**
func TestProperty_StoreDataConstructsCorrectToolParameters(t *testing.T) {
	rapid.Check(t, func(rt *rapid.T) {
		// Generate a random command string (1-100 chars, printable).
		command := rapid.StringMatching(`[a-zA-Z0-9 _\-\.\/]{1,100}`).Draw(rt, "command")

		// Generate a random description string (1-200 chars, printable).
		description := rapid.StringMatching(`[a-zA-Z0-9 _\-\.]{1,200}`).Draw(rt, "description")

		// Generate a random 384-dimension embedding vector.
		embedding := make([]float64, 384)
		for i := range embedding {
			embedding[i] = rapid.Float64Range(-1.0, 1.0).Draw(rt, fmt.Sprintf("emb_%d", i))
		}

		// Capture the tool call arguments.
		var captured toolCall
		c := newTestClient(func(ctx context.Context, toolName string, args map[string]any) (string, error) {
			captured = toolCall{toolName: toolName, args: args}
			return "", nil
		})

		err := c.StoreData(command, description, embedding, map[string]string{"source": "scmd"})
		if err != nil {
			rt.Fatalf("StoreData returned unexpected error: %v", err)
		}

		// 1. Tool name must be "store_data".
		if captured.toolName != "store_data" {
			rt.Fatalf("toolName = %q, want %q", captured.toolName, "store_data")
		}

		// 2. args["key"] must equal the generated command.
		if captured.args["key"] != command {
			rt.Fatalf("args[key] = %v, want %q", captured.args["key"], command)
		}

		// 3. args["content"] must equal the generated description.
		if captured.args["content"] != description {
			rt.Fatalf("args[content] = %v, want %q", captured.args["content"], description)
		}

		// 4. args["embedding"] must equal the generated 384-dim vector.
		emb, ok := captured.args["embedding"].([]float64)
		if !ok {
			rt.Fatalf("args[embedding] type = %T, want []float64", captured.args["embedding"])
		}
		if len(emb) != 384 {
			rt.Fatalf("len(embedding) = %d, want 384", len(emb))
		}
		for i, v := range emb {
			if v != embedding[i] {
				rt.Fatalf("embedding[%d] = %v, want %v", i, v, embedding[i])
			}
		}

		// 5. args["namespace"] must equal the client's namespace ("test-ns").
		if captured.args["namespace"] != "test-ns" {
			rt.Fatalf("args[namespace] = %v, want %q", captured.args["namespace"], "test-ns")
		}

		// 6. args["metadata"] must contain {"source": "scmd"} (converted to map[string]any).
		meta, ok := captured.args["metadata"].(map[string]any)
		if !ok {
			rt.Fatalf("args[metadata] type = %T, want map[string]any", captured.args["metadata"])
		}
		if meta["source"] != "scmd" {
			rt.Fatalf("metadata[source] = %v, want %q", meta["source"], "scmd")
		}
	})
}

// Feature: mcp-client-integration, Property 8: Command existence check matches on key
// **Validates: Requirements 13.1, 13.2**
func TestProperty_CommandExistenceCheckMatchesOnKey(t *testing.T) {
	rapid.Check(t, func(rt *rapid.T) {
		// Generate a random set of MCPRecords (1-20 records) with random keys.
		numRecords := rapid.IntRange(1, 20).Draw(rt, "numRecords")
		records := make([]MCPRecord, numRecords)
		keys := make([]string, numRecords)
		for i := 0; i < numRecords; i++ {
			key := rapid.StringMatching(`[a-zA-Z0-9 _\-\.\/]{1,80}`).Draw(rt, fmt.Sprintf("key_%d", i))
			keys[i] = key
			records[i] = MCPRecord{
				ID:      fmt.Sprintf("uuid-%d", i),
				Key:     key,
				Content: rapid.String().Draw(rt, fmt.Sprintf("content_%d", i)),
			}
		}

		// Decide whether to test the true case (query matches a key) or false case.
		testTrueCase := rapid.Bool().Draw(rt, "testTrueCase")

		if testTrueCase {
			// Pick one of the existing keys as the query.
			idx := rapid.IntRange(0, numRecords-1).Draw(rt, "pickIdx")
			query := keys[idx]

			result := CheckCommandExists(records, query)
			if !result {
				rt.Fatalf("CheckCommandExists returned false for query %q which exists in records", query)
			}
		} else {
			// Generate a query that is NOT in the set of keys.
			// Use a prefix that cannot be generated by the key pattern above.
			query := "##NOTAKEY##" + rapid.String().Draw(rt, "uniqueSuffix")

			result := CheckCommandExists(records, query)
			if result {
				rt.Fatalf("CheckCommandExists returned true for query %q which should not match any record key", query)
			}
		}

		// Additionally verify that partial matches do not count:
		// Append extra text to an existing key and confirm it does not match.
		idx := rapid.IntRange(0, numRecords-1).Draw(rt, "partialIdx")
		partialQuery := keys[idx] + "EXTRA"
		if CheckCommandExists(records, partialQuery) {
			rt.Fatalf("CheckCommandExists returned true for partial query %q (original key %q)", partialQuery, keys[idx])
		}
	})
}

// Feature: mcp-client-integration, Property 10: Pagination parameters pass through to list_data
// **Validates: Requirements 8.2, 5.5**
func TestProperty_PaginationParametersPassThroughToListData(t *testing.T) {
	rapid.Check(t, func(rt *rapid.T) {
		// Generate random non-negative limit and offset values.
		limit := rapid.IntRange(0, math.MaxInt32).Draw(rt, "limit")
		offset := rapid.IntRange(0, math.MaxInt32).Draw(rt, "offset")

		// Capture the tool call arguments.
		var captured toolCall
		c := newTestClient(func(ctx context.Context, toolName string, args map[string]any) (string, error) {
			captured = toolCall{toolName: toolName, args: args}
			return `{"records":[],"total_count":0}`, nil
		})

		_, err := c.ListData(c.namespace, limit, offset)
		if err != nil {
			rt.Fatalf("ListData returned unexpected error: %v", err)
		}

		// 1. Tool name must be "list_data".
		if captured.toolName != "list_data" {
			rt.Fatalf("toolName = %q, want %q", captured.toolName, "list_data")
		}

		// 2. args["limit"] must equal the generated limit value.
		if captured.args["limit"] != limit {
			rt.Fatalf("args[limit] = %v, want %d", captured.args["limit"], limit)
		}

		// 3. args["offset"] must equal the generated offset value.
		if captured.args["offset"] != offset {
			rt.Fatalf("args[offset] = %v, want %d", captured.args["offset"], offset)
		}

		// 4. args["namespace"] must be passed through correctly.
		if captured.args["namespace"] != "test-ns" {
			rt.Fatalf("args[namespace] = %v, want %q", captured.args["namespace"], "test-ns")
		}
	})
}
