package mcpclient

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"testing"

	"pgregory.net/rapid"
)

// Feature: mcp-client-integration, Property 3: Invalid JSON produces parse error
// **Validates: Requirements 2.4**
func TestProperty_InvalidJSONProducesParseError(t *testing.T) {
	rapid.Check(t, func(rt *rapid.T) {
		// Generate random byte sequences of length 1-512.
		length := rapid.IntRange(1, 512).Draw(rt, "length")
		data := make([]byte, length)
		for i := range data {
			data[i] = rapid.Byte().Draw(rt, fmt.Sprintf("byte_%d", i))
		}

		// Filter out any byte sequences that happen to be valid JSON.
		if json.Valid(data) {
			rt.Skip("generated bytes are valid JSON, skipping")
		}

		// Write the invalid JSON to a temp file.
		dir := t.TempDir()
		path := filepath.Join(dir, "mcp_server.json")
		if err := os.WriteFile(path, data, 0600); err != nil {
			rt.Fatalf("failed to write temp file: %v", err)
		}

		// ParseConfig should return a non-nil error for invalid JSON.
		_, _, err := ParseConfig(path)
		if err == nil {
			rt.Fatalf("expected non-nil error for invalid JSON, got nil (data=%q)", data)
		}
	})
}

// Feature: mcp-client-integration, Property 2: MCP server config parsing round-trip
// **Validates: Requirements 2.1**
func TestProperty_MCPServerConfigParsingRoundTrip(t *testing.T) {
	rapid.Check(t, func(rt *rapid.T) {
		// Generate between 1 and 5 server entries.
		numEntries := rapid.IntRange(1, 5).Draw(rt, "numEntries")

		servers := make(map[string]MCPServerEntry, numEntries)
		for i := 0; i < numEntries; i++ {
			// Generate a valid server name: alphanumeric with hyphens, 1-30 chars.
			name := rapid.StringMatching(`[a-zA-Z][a-zA-Z0-9\-]{0,29}`).Draw(rt, "serverName")

			// Generate a valid URL with scheme, host, and optional path.
			scheme := rapid.SampledFrom([]string{"http", "https"}).Draw(rt, "scheme")
			host := rapid.StringMatching(`[a-z]{1,10}\.[a-z]{2,5}`).Draw(rt, "host")
			port := rapid.IntRange(1, 65535).Draw(rt, "port")
			path := rapid.SampledFrom([]string{"/sse", "/mcp", "/events", "/api/sse"}).Draw(rt, "path")

			url := fmt.Sprintf("%s://%s:%d%s", scheme, host, port, path)

			servers[name] = MCPServerEntry{URL: url}
		}

		cfg := MCPServerConfig{
			MCPServers: servers,
		}

		// Serialize to JSON.
		data, err := json.Marshal(cfg)
		if err != nil {
			rt.Fatalf("failed to marshal config: %v", err)
		}

		// Write to a temp file.
		dir := t.TempDir()
		path := filepath.Join(dir, "mcp_server.json")
		if err := os.WriteFile(path, data, 0600); err != nil {
			rt.Fatalf("failed to write config file: %v", err)
		}

		// Parse with ParseConfig.
		gotName, gotEndpoint, err := ParseConfig(path)
		if err != nil {
			rt.Fatalf("ParseConfig returned error: %v", err)
		}

		// Since Go map iteration order is random, ParseConfig returns the first
		// entry it encounters. Verify the returned name+URL pair exists in the
		// original map.
		entry, ok := servers[gotName]
		if !ok {
			rt.Fatalf("ParseConfig returned server name %q which is not in the original map", gotName)
		}
		if gotEndpoint != entry.URL {
			rt.Fatalf("ParseConfig returned endpoint %q for server %q, want %q", gotEndpoint, gotName, entry.URL)
		}

		// Verify the returned name is non-empty.
		if gotName == "" {
			rt.Fatal("ParseConfig returned empty server name")
		}

		// Verify the returned endpoint is non-empty.
		if gotEndpoint == "" {
			rt.Fatal("ParseConfig returned empty endpoint")
		}
	})
}
